# Generated by Django 5.2.6 on 2025-09-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoiceitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated tax amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='taxinvoiceitem',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='Tax rate for this item', max_digits=5),
        ),
    ]
