# Generated by Django 5.2.6 on 2025-10-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_taxinvoiceitem_tax_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxinvoice',
            name='company_gstin',
            field=models.CharField(default='', max_length=15),
        ),
    ]
