# Generated by Django 5.2.6 on 2025-10-09 09:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_taxinvoice_company_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxinvoice',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='taxinvoice',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='taxinvoiceitem',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Tax rate for this item', max_digits=5),
        ),
    ]
