# Generated by Django 5.2.6 on 2025-09-19 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address'),
        ('orders', '0004_alter_cartitem_unique_together_cartitem_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.address'),
        ),
    ]
