# Generated by Django 5.2.6 on 2025-09-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_selected_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_email_error',
            field=models.TextField(blank=True, help_text='Error message if confirmation email failed'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False, help_text='Order confirmation email sent'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmation_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When confirmation email was sent', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_email_error',
            field=models.TextField(blank=True, help_text='Error message if invoice email failed'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_email_sent',
            field=models.BooleanField(default=False, help_text='Invoice email sent'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When invoice email was sent', null=True),
        ),
    ]
