# Generated by Django 5.2.6 on 2025-09-25 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_confirmation_email_error_and_more'),
        ('products', '0007_combo_comboitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='products.combo'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='combo_group',
            field=models.CharField(blank=True, help_text='UUID to group items belonging to one combo instance', max_length=36, null=True),
        ),
        migrations.CreateModel(
            name='CartCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_group', models.CharField(help_text='UUID identifying this combo instance in the cart', max_length=36)),
                ('original_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('combo_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='orders.cart')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.combo')),
            ],
            options={
                'indexes': [models.Index(fields=['combo_group'], name='orders_cart_combo_g_4d10ad_idx')],
            },
        ),
    ]
