# Generated by Django 5.2.6 on 2025-09-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_aggregate_stock_productstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='HSN (Harmonized System of Nomenclature) code for GST', max_length=10, null=True),
        ),
    ]
