# Generated by Django 5.2.6 on 2025-09-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_hsn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='GST tax rate for this product (e.g., 18.00 for 18%)', max_digits=5),
        ),
    ]
