# Generated by Django 5.2.6 on 2025-09-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, help_text='Default GST tax rate for all products in this category (e.g., 18.00 for 18%)', max_digits=5),
        ),
    ]
