# Generated by Django 5.2.6 on 2025-09-25 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_combo_comboitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='combos/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.combo')),
            ],
        ),
    ]
